twoja_litera = 'K'
wynik=[]
index=[]
_max=0
uczen_nr_3 = [
"YECHPAPSBCOLHYGDNMFKLWYFFABLIPULLOFIMHCZ",
"IXSWZNKTKHQXBFFZMEDQLLHEJLRMZGINXZVBFZOW",
"MBVNESOHMYQXKVYUUHOUJKDJYBUKYWDPGGRKTUOH",
"VHCSXPELELVUKFPZZOADSLEUJKWAQDHODZBTFOCB",
"LTUQCBOIWCCDJGFOHIZDPIMSHDJNOKXGFMESEGLL",
"OORIFZVBQYJITJNMKSNHMXCBJOSPQERSEIENVDIM",
"HIXJKPSZFNCYOKKWBTEXIUGLJXKTONDGLGYVGRGB",
"AQKYMPPCITVUSFNLJUSLUCTDZTRURSXEZCHIGTQT",
"VSVZYANDEQCDQHFUXPPHFOQIPOHPICYXPFUSRXLV",
"QIEVLSPSYPIOVTEXVUPVGJDRWLHHICEHPLFVQBBN",
"EHKTEWGJKMARHSVLDGPRGNNPDPQWMNOGPIRMWWDH",
"RALFKWPOCOVGVJASCBQOPINWEEQXNVRNEROGDXGF",
"KDRYKAJBSIJGHMKNBQRVMTOGTYRFYFORZDGMEFGS",
"SHHDDWBPCCHEKSZTFSFTSRCCAJELVCIBDUIJIARC",
"YVGXCTSPESBWUUXBFLZCTXFPTMZMYVCLSBLQSDHZ",
"HCZLUGKMMFIXYNVYJZOBQZOUTTXBKVYROLVFCGUM",
"RKYRTPMWVHLWYUYVVBFTZTCCERNKFCRPXKESIQBN",
"SAWHGBZTSWWDWCXOYKNPOZWIGKWMTZSIPETHLIYK",
"SSNIEETLDVMSIYMCGUMSSSXGKBQXYKRZZGZSELDJ",
"AXIQPDHXJEKMOEVWFOVOYHAYOEZNCGTMMUTOSMPJ"
]
for i,line in enumerate(uczen_nr_3):
    res = list(filter(lambda x: x.upper()==twoja_litera.upper(), line))
    if len(res)>_max:
        _max=len(res)
    wynik.append([len(res),i])
for i,line in enumerate(wynik):
    if line[0]==_max:
        index.append(line[1])
string=("".join(str(index)))
print(f'Ilość znaków ({twoja_litera.upper()}): {_max}\n Indeksy: {string.replace("[","").replace("]","")} ')
